import { ModelMetadata } from "./types";

export const MODELS_DATA: ModelMetadata[] = [
  {
    company: "Anthropic",
    modelName: "Claude Sonnet 4",
    modelIdentifier: "claude-sonnet-4",
    context: 200000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["anthropic", "bedrock", "vertexanthropic"],
    releaseDate: "2025-05-22",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Anthropic",
    modelName: "Claude 3.7 Sonnet",
    modelIdentifier: "claude-3.7-sonnet",
    context: 200000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["anthropic", "bedrock", "vertexanthropic"],
    releaseDate: "2025-02-24",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "OpenAI",
    modelName: "GPT-5 nano",
    modelIdentifier: "gpt-5-nano",
    context: 400000,
    usdCostPerMillionInputTokens: 0.05,
    usdCostPerMillionOutputTokens: 0.4,
    providers: ["openai"],
    releaseDate: "2025-08-07",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "GPT-5",
    modelIdentifier: "gpt-5",
    context: 400000,
    usdCostPerMillionInputTokens: 1.25,
    usdCostPerMillionOutputTokens: 10,
    providers: ["openai"],
    releaseDate: "2025-08-07",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Gemini 2.0 Flash",
    modelIdentifier: "gemini-2.0-flash",
    context: 1000000,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: 0.6,
    providers: ["google", "vertex"],
    releaseDate: "2024-12-11",
    tier: "normal",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Gemini 2.5 Flash",
    modelIdentifier: "gemini-2.5-flash",
    context: 1000000,
    usdCostPerMillionInputTokens: 0.3,
    usdCostPerMillionOutputTokens: 2.5,
    providers: ["google", "vertex"],
    releaseDate: "2025-01-15",
    tier: "normal",
    canGenerateImage: true,
    hasReasoning: true,
  },
  {
    company: "OpenAI",
    modelName: "GPT-4o mini",
    modelIdentifier: "gpt-4o-mini",
    context: 128000,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: 0.6,
    providers: ["openai", "azure"],
    releaseDate: "2024-07-18",
    tier: "small",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Anthropic",
    modelName: "Claude Opus 4.1",
    modelIdentifier: "claude-opus-4.1",
    context: 200000,
    usdCostPerMillionInputTokens: 15,
    usdCostPerMillionOutputTokens: 75,
    providers: ["anthropic"],
    releaseDate: "2025-05-22",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "gpt-oss-120b",
    modelIdentifier: "gpt-oss-120b",
    context: 131000,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: 0.5,
    providers: ["openai", "baseten", "cerebras", "fireworks"],
    releaseDate: "2025-01-15",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "GPT-5 mini",
    modelIdentifier: "gpt-5-mini",
    context: 400000,
    usdCostPerMillionInputTokens: 0.25,
    usdCostPerMillionOutputTokens: 2,
    providers: ["openai"],
    releaseDate: "2025-08-07",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "GPT-4o",
    modelIdentifier: "gpt-4o",
    context: 128000,
    usdCostPerMillionInputTokens: 2.5,
    usdCostPerMillionOutputTokens: 10,
    providers: ["openai", "azure"],
    releaseDate: "2024-05-13",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "text-embedding-3-small",
    modelIdentifier: "text-embedding-3-small",
    context: null,
    usdCostPerMillionInputTokens: 0.02,
    usdCostPerMillionOutputTokens: null,
    providers: ["openai", "azure"],
    releaseDate: "2024-01-25",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "DeepSeek",
    modelName: "DeepSeek R1",
    modelIdentifier: "deepseek-r1",
    context: 160000,
    usdCostPerMillionInputTokens: 0.79,
    usdCostPerMillionOutputTokens: 4,
    providers: ["deepseek", "baseten", "bedrock", "fireworks"],
    releaseDate: "2025-05-28",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "OpenAI",
    modelName: "gpt-oss-20b",
    modelIdentifier: "gpt-oss-20b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.07,
    usdCostPerMillionOutputTokens: 0.3,
    providers: ["openai", "fireworks", "groq"],
    releaseDate: "2025-01-15",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Moonshot AI",
    modelName: "Kimi K2",
    modelIdentifier: "kimi-k2",
    context: 131000,
    usdCostPerMillionInputTokens: 0.5,
    usdCostPerMillionOutputTokens: 2,
    providers: ["moonshotai", "baseten", "deepinfra", "fireworks"],
    releaseDate: "2024-10-15",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Alibaba Cloud",
    modelName: "Qwen3 Coder",
    modelIdentifier: "qwen3-coder",
    context: 131000,
    usdCostPerMillionInputTokens: 0.4,
    usdCostPerMillionOutputTokens: 1.6,
    providers: ["alibaba", "baseten", "cerebras", "deepinfra"],
    releaseDate: "2024-11-20",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Gemini 2.5 Pro",
    modelIdentifier: "gemini-2.5-pro",
    context: 1000000,
    usdCostPerMillionInputTokens: 2.5,
    usdCostPerMillionOutputTokens: 10,
    providers: ["google", "vertex"],
    releaseDate: "2025-01-15",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: true,
  },
  {
    company: "Google",
    modelName: "Gemini 2.5 Flash Lite",
    modelIdentifier: "gemini-2.5-flash-lite",
    context: 1000000,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: 0.4,
    providers: ["google", "vertex"],
    releaseDate: "2025-01-15",
    tier: "small",
    canGenerateImage: true,
    hasReasoning: true,
  },
  {
    company: "DeepSeek",
    modelName: "DeepSeek V3.1 Thinking",
    modelIdentifier: "deepseek-v3.1-thinking",
    context: 128000,
    usdCostPerMillionInputTokens: 0.56,
    usdCostPerMillionOutputTokens: 1.68,
    providers: ["deepseek"],
    releaseDate: "2025-08-21",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "OpenAI",
    modelName: "GPT-4.1",
    modelIdentifier: "gpt-4.1",
    context: 1000000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 8,
    providers: ["openai", "azure"],
    releaseDate: "2025-01-30",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "DeepSeek",
    modelName: "DeepSeek V3.1",
    modelIdentifier: "deepseek-v3.1",
    context: 164000,
    usdCostPerMillionInputTokens: 0.2,
    usdCostPerMillionOutputTokens: 0.8,
    providers: ["deepseek", "chutes", "deepinfra"],
    releaseDate: "2025-08-21",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Z.ai",
    modelName: "GLM 4.5",
    modelIdentifier: "glm-4.5",
    context: 128000,
    usdCostPerMillionInputTokens: 0.6,
    usdCostPerMillionOutputTokens: 2.2,
    providers: ["zai", "novita"],
    releaseDate: "2024-09-15",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Gemini 2.0 Flash Lite",
    modelIdentifier: "gemini-2.0-flash-lite",
    context: 1000000,
    usdCostPerMillionInputTokens: 0.07,
    usdCostPerMillionOutputTokens: 0.3,
    providers: ["google", "vertex"],
    releaseDate: "2024-12-11",
    tier: "small",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "xAI",
    modelName: "Grok 4",
    modelIdentifier: "grok-4",
    context: 256000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["xai"],
    releaseDate: "2025-01-15",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "GPT-4.1 mini",
    modelIdentifier: "gpt-4.1-mini",
    context: 1000000,
    usdCostPerMillionInputTokens: 0.4,
    usdCostPerMillionOutputTokens: 1.6,
    providers: ["openai", "azure"],
    releaseDate: "2025-01-30",
    tier: "normal",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Anthropic",
    modelName: "Claude Opus 4",
    modelIdentifier: "claude-opus-4",
    context: 200000,
    usdCostPerMillionInputTokens: 15,
    usdCostPerMillionOutputTokens: 75,
    providers: ["anthropic", "bedrock", "vertexanthropic"],
    releaseDate: "2025-05-22",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "o4-mini",
    modelIdentifier: "o4-mini",
    context: 200000,
    usdCostPerMillionInputTokens: 1.1,
    usdCostPerMillionOutputTokens: 4.4,
    providers: ["openai", "azure"],
    releaseDate: "2025-03-15",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "Alibaba Cloud",
    modelName: "Qwen 3.32B",
    modelIdentifier: "qwen-3-32b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: 0.3,
    providers: ["alibaba", "cerebras", "deepinfra", "groq"],
    releaseDate: "2024-11-20",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Anthropic",
    modelName: "Claude 3.5 Sonnet",
    modelIdentifier: "claude-3.5-sonnet",
    context: 200000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["anthropic", "bedrock", "vertexanthropic"],
    releaseDate: "2024-06-20",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Anthropic",
    modelName: "Claude 3.5 Haiku",
    modelIdentifier: "claude-3.5-haiku",
    context: 200000,
    usdCostPerMillionInputTokens: 0.8,
    usdCostPerMillionOutputTokens: 4,
    providers: ["anthropic", "bedrock", "vertexanthropic"],
    releaseDate: "2024-10-22",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "o3-mini",
    modelIdentifier: "o3-mini",
    context: 200000,
    usdCostPerMillionInputTokens: 1.1,
    usdCostPerMillionOutputTokens: 4.4,
    providers: ["openai", "azure"],
    releaseDate: "2024-12-20",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "OpenAI",
    modelName: "GPT-4.1 nano",
    modelIdentifier: "gpt-4.1-nano",
    context: 1000000,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: 0.4,
    providers: ["openai", "azure"],
    releaseDate: "2025-01-30",
    tier: "small",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "xAI",
    modelName: "Grok 3 Beta",
    modelIdentifier: "grok-3",
    context: 131000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["xai"],
    releaseDate: "2024-11-15",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Alibaba Cloud",
    modelName: "Qwen3 235B A22B Instruct 2507",
    modelIdentifier: "qwen-3-235b",
    context: 262000,
    usdCostPerMillionInputTokens: 0.13,
    usdCostPerMillionOutputTokens: 0.6,
    providers: ["alibaba", "baseten", "deepinfra", "fireworks"],
    releaseDate: "2024-11-20",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Alibaba Cloud",
    modelName: "Qwen3-14B",
    modelIdentifier: "qwen-3-14b",
    context: 41000,
    usdCostPerMillionInputTokens: 0.06,
    usdCostPerMillionOutputTokens: 0.24,
    providers: ["alibaba", "deepinfra"],
    releaseDate: "2024-11-20",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3.3 70B",
    modelIdentifier: "llama-3.3-70b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.72,
    usdCostPerMillionOutputTokens: 0.72,
    providers: ["meta", "bedrock", "cerebras", "groq"],
    releaseDate: "2024-12-06",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "text-embedding-3-large",
    modelIdentifier: "text-embedding-3-large",
    context: null,
    usdCostPerMillionInputTokens: 0.13,
    usdCostPerMillionOutputTokens: null,
    providers: ["openai", "azure"],
    releaseDate: "2024-01-25",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "o3",
    modelIdentifier: "o3",
    context: 200000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 8,
    providers: ["openai"],
    releaseDate: "2024-12-20",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "Perplexity",
    modelName: "Sonar",
    modelIdentifier: "sonar",
    context: 127000,
    usdCostPerMillionInputTokens: 1,
    usdCostPerMillionOutputTokens: 1,
    providers: ["perplexity"],
    releaseDate: "2024-08-15",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Amazon Bedrock",
    modelName: "Nova Pro",
    modelIdentifier: "nova-pro",
    context: 300000,
    usdCostPerMillionInputTokens: 0.8,
    usdCostPerMillionOutputTokens: 3.2,
    providers: ["amazon", "bedrock"],
    releaseDate: "2024-12-03",
    tier: "normal",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 4 Scout",
    modelIdentifier: "llama-4-scout",
    context: 128000,
    usdCostPerMillionInputTokens: 0.08,
    usdCostPerMillionOutputTokens: 0.3,
    providers: ["meta", "baseten", "bedrock", "cerebras"],
    releaseDate: "2025-01-10",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Mistral Small",
    modelIdentifier: "mistral-small",
    context: 32000,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: 0.3,
    providers: ["mistral"],
    releaseDate: "2024-02-26",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "DeepSeek",
    modelName: "DeepSeek R1 Distill Llama 70B",
    modelIdentifier: "deepseek-r1-distill-llama-70b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.75,
    usdCostPerMillionOutputTokens: 0.99,
    providers: ["deepseek", "cerebras", "groq"],
    releaseDate: "2025-06-15",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "Vercel",
    modelName: "v0-1.5-md",
    modelIdentifier: "v0-1.5-md",
    context: 128000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["vercel"],
    releaseDate: "2024-11-01",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Z.ai",
    modelName: "GLM 4.5 Air",
    modelIdentifier: "glm-4.5-air",
    context: 128000,
    usdCostPerMillionInputTokens: 0.2,
    usdCostPerMillionOutputTokens: 1.1,
    providers: ["zai"],
    releaseDate: "2024-09-15",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3.1 8B",
    modelIdentifier: "llama-3.1-8b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.05,
    usdCostPerMillionOutputTokens: 0.08,
    providers: ["meta", "bedrock", "cerebras", "groq"],
    releaseDate: "2024-07-23",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "xAI",
    modelName: "Grok 3 Mini Beta",
    modelIdentifier: "grok-3-mini",
    context: 131000,
    usdCostPerMillionInputTokens: 0.3,
    usdCostPerMillionOutputTokens: 0.5,
    providers: ["xai"],
    releaseDate: "2024-11-15",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "xAI",
    modelName: "Grok 3 Fast Beta",
    modelIdentifier: "grok-3-fast",
    context: 131000,
    usdCostPerMillionInputTokens: 5,
    usdCostPerMillionOutputTokens: 25,
    providers: ["xai"],
    releaseDate: "2024-11-15",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Anthropic",
    modelName: "Claude 3 Haiku",
    modelIdentifier: "claude-3-haiku",
    context: 200000,
    usdCostPerMillionInputTokens: 0.25,
    usdCostPerMillionOutputTokens: 1.25,
    providers: ["anthropic", "bedrock", "vertexanthropic"],
    releaseDate: "2024-03-07",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Perplexity",
    modelName: "Sonar Pro",
    modelIdentifier: "sonar-pro",
    context: 200000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["perplexity"],
    releaseDate: "2024-08-15",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 4 Maverick 17B 128E Instruct",
    modelIdentifier: "llama-4-maverick",
    context: 1000000,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: 0.6,
    providers: ["meta", "baseten", "bedrock", "deepinfra"],
    releaseDate: "2025-01-10",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Perplexity",
    modelName: "Sonar Reasoning",
    modelIdentifier: "sonar-reasoning",
    context: 127000,
    usdCostPerMillionInputTokens: 1,
    usdCostPerMillionOutputTokens: 5,
    providers: ["perplexity"],
    releaseDate: "2024-12-01",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "OpenAI",
    modelName: "GPT-3.5 Turbo",
    modelIdentifier: "gpt-3.5-turbo",
    context: 16000,
    usdCostPerMillionInputTokens: 0.5,
    usdCostPerMillionOutputTokens: 1.5,
    providers: ["openai"],
    releaseDate: "2023-03-01",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "xAI",
    modelName: "Grok 2",
    modelIdentifier: "grok-2",
    context: 131000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 10,
    providers: ["xai"],
    releaseDate: "2024-08-13",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Morph",
    modelName: "Morph V3 Fast",
    modelIdentifier: "morph-v3-fast",
    context: 33000,
    usdCostPerMillionInputTokens: 0.8,
    usdCostPerMillionOutputTokens: 1.2,
    providers: ["morph"],
    releaseDate: "2024-09-01",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "xAI",
    modelName: "Grok 2 Vision",
    modelIdentifier: "grok-2-vision",
    context: 33000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 10,
    providers: ["xai"],
    releaseDate: "2024-08-13",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "GPT-4 Turbo",
    modelIdentifier: "gpt-4-turbo",
    context: 128000,
    usdCostPerMillionInputTokens: 10,
    usdCostPerMillionOutputTokens: 30,
    providers: ["openai"],
    releaseDate: "2024-04-09",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "xAI",
    modelName: "Grok 3 Mini Fast Beta",
    modelIdentifier: "grok-3-mini-fast",
    context: 131000,
    usdCostPerMillionInputTokens: 0.6,
    usdCostPerMillionOutputTokens: 4,
    providers: ["xai"],
    releaseDate: "2024-11-15",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Perplexity",
    modelName: "Sonar Reasoning Pro",
    modelIdentifier: "sonar-reasoning-pro",
    context: 127000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 8,
    providers: ["perplexity"],
    releaseDate: "2024-12-01",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "Mistral",
    modelName: "Mistral Large",
    modelIdentifier: "mistral-large",
    context: 32000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 6,
    providers: ["mistral"],
    releaseDate: "2024-02-26",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Vercel",
    modelName: "v0-1.0-md",
    modelIdentifier: "v0-1.0-md",
    context: 128000,
    usdCostPerMillionInputTokens: 3,
    usdCostPerMillionOutputTokens: 15,
    providers: ["vercel"],
    releaseDate: "2024-09-01",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Mistral Codestral 25.01",
    modelIdentifier: "codestral",
    context: 256000,
    usdCostPerMillionInputTokens: 0.3,
    usdCostPerMillionOutputTokens: 0.9,
    providers: ["mistral"],
    releaseDate: "2025-01-15",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Alibaba Cloud",
    modelName: "Qwen3-30B-A3B",
    modelIdentifier: "qwen-3-30b",
    context: 41000,
    usdCostPerMillionInputTokens: 0.08,
    usdCostPerMillionOutputTokens: 0.29,
    providers: ["alibaba", "deepinfra"],
    releaseDate: "2024-11-20",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "DeepSeek",
    modelName: "DeepSeek V3 0324",
    modelIdentifier: "deepseek-v3",
    context: 164000,
    usdCostPerMillionInputTokens: 0.77,
    usdCostPerMillionOutputTokens: 0.77,
    providers: ["deepseek", "baseten", "fireworks", "novita"],
    releaseDate: "2024-03-24",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "o1",
    modelIdentifier: "o1",
    context: 200000,
    usdCostPerMillionInputTokens: 15,
    usdCostPerMillionOutputTokens: 60,
    providers: ["openai", "azure"],
    releaseDate: "2024-09-12",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: true,
  },
  {
    company: "DeepSeek",
    modelName: "DeepSeek V3.1 Base",
    modelIdentifier: "deepseek-v3.1-base",
    context: 128000,
    usdCostPerMillionInputTokens: 0.2,
    usdCostPerMillionOutputTokens: 0.8,
    providers: ["deepseek", "chutes"],
    releaseDate: "2025-08-21",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Anthropic",
    modelName: "Claude 3 Opus",
    modelIdentifier: "claude-3-opus",
    context: 200000,
    usdCostPerMillionInputTokens: 15,
    usdCostPerMillionOutputTokens: 75,
    providers: ["anthropic", "bedrock", "vertexanthropic"],
    releaseDate: "2024-03-04",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Amazon Bedrock",
    modelName: "Nova Micro",
    modelIdentifier: "nova-micro",
    context: 128000,
    usdCostPerMillionInputTokens: 0.04,
    usdCostPerMillionOutputTokens: 0.14,
    providers: ["amazon", "bedrock"],
    releaseDate: "2024-12-03",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Gemma 2 9B IT",
    modelIdentifier: "gemma-2-9b",
    context: 8000,
    usdCostPerMillionInputTokens: 0.2,
    usdCostPerMillionOutputTokens: 0.2,
    providers: ["google", "groq"],
    releaseDate: "2024-06-27",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Ministral 3B",
    modelIdentifier: "ministral-3b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.04,
    usdCostPerMillionOutputTokens: 0.04,
    providers: ["mistral"],
    releaseDate: "2024-10-16",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Mistral Medium 3.1",
    modelIdentifier: "mistral-medium",
    context: 128000,
    usdCostPerMillionInputTokens: 0.4,
    usdCostPerMillionOutputTokens: 2,
    providers: ["mistral"],
    releaseDate: "2024-12-11",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Magistral Medium 2506",
    modelIdentifier: "magistral-medium",
    context: 128000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 5,
    providers: ["mistral"],
    releaseDate: "2025-06-01",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Text Embedding 005",
    modelIdentifier: "text-embedding-005",
    context: null,
    usdCostPerMillionInputTokens: 0.03,
    usdCostPerMillionOutputTokens: null,
    providers: ["google", "vertex"],
    releaseDate: "2024-09-24",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Cohere",
    modelName: "Embed v4.0",
    modelIdentifier: "embed-v4.0",
    context: null,
    usdCostPerMillionInputTokens: 0.12,
    usdCostPerMillionOutputTokens: null,
    providers: ["cohere"],
    releaseDate: "2024-11-01",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Amazon Bedrock",
    modelName: "Nova Lite",
    modelIdentifier: "nova-lite",
    context: 300000,
    usdCostPerMillionInputTokens: 0.06,
    usdCostPerMillionOutputTokens: 0.24,
    providers: ["amazon", "bedrock"],
    releaseDate: "2024-12-03",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "text-embedding-ada-002",
    modelIdentifier: "text-embedding-ada-002",
    context: null,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: null,
    providers: ["openai", "azure"],
    releaseDate: "2022-12-15",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3.2 1B Instruct",
    modelIdentifier: "llama-3.2-1b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: 0.1,
    providers: ["meta", "bedrock"],
    releaseDate: "2024-09-25",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Gemini Embedding 001",
    modelIdentifier: "gemini-embedding-001",
    context: null,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: null,
    providers: ["google", "vertex"],
    releaseDate: "2024-02-15",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "OpenAI",
    modelName: "GPT-3.5 Turbo Instruct",
    modelIdentifier: "gpt-3.5-turbo-instruct",
    context: 8000,
    usdCostPerMillionInputTokens: 1.5,
    usdCostPerMillionOutputTokens: 2,
    providers: ["openai"],
    releaseDate: "2023-09-20",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3 70B Instruct",
    modelIdentifier: "llama-3-70b",
    context: 8000,
    usdCostPerMillionInputTokens: 0.59,
    usdCostPerMillionOutputTokens: 0.79,
    providers: ["meta", "groq"],
    releaseDate: "2024-04-18",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Amazon Bedrock",
    modelName: "Titan Text Embeddings V2",
    modelIdentifier: "titan-embed-text-v2",
    context: null,
    usdCostPerMillionInputTokens: 0.02,
    usdCostPerMillionOutputTokens: null,
    providers: ["amazon", "bedrock"],
    releaseDate: "2024-04-30",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Cohere",
    modelName: "Command A",
    modelIdentifier: "command-a",
    context: 256000,
    usdCostPerMillionInputTokens: 2.5,
    usdCostPerMillionOutputTokens: 10,
    providers: ["cohere"],
    releaseDate: "2024-08-01",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Cohere",
    modelName: "Command R",
    modelIdentifier: "command-r",
    context: 128000,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: 0.6,
    providers: ["cohere"],
    releaseDate: "2024-03-11",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Cohere",
    modelName: "Command R+",
    modelIdentifier: "command-r-plus",
    context: 128000,
    usdCostPerMillionInputTokens: 2.5,
    usdCostPerMillionOutputTokens: 10,
    providers: ["cohere"],
    releaseDate: "2024-04-04",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Google",
    modelName: "Text Multilingual Embedding 002",
    modelIdentifier: "text-multilingual-embedding-002",
    context: null,
    usdCostPerMillionInputTokens: 0.03,
    usdCostPerMillionOutputTokens: null,
    providers: ["google", "vertex"],
    releaseDate: "2024-04-10",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Inception",
    modelName: "Mercury Coder Small Beta",
    modelIdentifier: "mercury-coder-small",
    context: 32000,
    usdCostPerMillionInputTokens: 0.25,
    usdCostPerMillionOutputTokens: 1,
    providers: ["inception"],
    releaseDate: "2024-10-01",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3 8B Instruct",
    modelIdentifier: "llama-3-8b",
    context: 8000,
    usdCostPerMillionInputTokens: 0.05,
    usdCostPerMillionOutputTokens: 0.08,
    providers: ["meta", "groq"],
    releaseDate: "2024-04-18",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3.1 70B Instruct",
    modelIdentifier: "llama-3.1-70b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.72,
    usdCostPerMillionOutputTokens: 0.72,
    providers: ["meta", "bedrock"],
    releaseDate: "2024-07-23",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3.2 11B Vision Instruct",
    modelIdentifier: "llama-3.2-11b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.16,
    usdCostPerMillionOutputTokens: 0.16,
    providers: ["meta", "bedrock"],
    releaseDate: "2024-09-25",
    tier: "normal",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3.2 3B Instruct",
    modelIdentifier: "llama-3.2-3b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: 0.15,
    providers: ["meta", "bedrock"],
    releaseDate: "2024-09-25",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Meta",
    modelName: "Llama 3.2 90B Vision Instruct",
    modelIdentifier: "llama-3.2-90b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.72,
    usdCostPerMillionOutputTokens: 0.72,
    providers: ["meta", "bedrock"],
    releaseDate: "2024-09-25",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Codestral Embed",
    modelIdentifier: "codestral-embed",
    context: null,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: null,
    providers: ["mistral"],
    releaseDate: "2024-05-29",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Devstral Small",
    modelIdentifier: "devstral-small",
    context: 128000,
    usdCostPerMillionInputTokens: 0.07,
    usdCostPerMillionOutputTokens: 0.28,
    providers: ["mistral", "deepinfra"],
    releaseDate: "2024-11-01",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Magistral Small 2506",
    modelIdentifier: "magistral-small",
    context: 128000,
    usdCostPerMillionInputTokens: 0.5,
    usdCostPerMillionOutputTokens: 1.5,
    providers: ["mistral"],
    releaseDate: "2025-06-01",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Ministral 8B",
    modelIdentifier: "ministral-8b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: 0.1,
    providers: ["mistral"],
    releaseDate: "2024-10-16",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Mistral Embed",
    modelIdentifier: "mistral-embed",
    context: null,
    usdCostPerMillionInputTokens: 0.1,
    usdCostPerMillionOutputTokens: null,
    providers: ["mistral"],
    releaseDate: "2023-12-11",
    tier: "small",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Mistral Saba 24B",
    modelIdentifier: "mistral-saba-24b",
    context: 33000,
    usdCostPerMillionInputTokens: 0.79,
    usdCostPerMillionOutputTokens: 0.79,
    providers: ["mistral", "groq"],
    releaseDate: "2024-12-11",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Mixtral MoE 8x22B Instruct",
    modelIdentifier: "mixtral-8x22b-instruct",
    context: 66000,
    usdCostPerMillionInputTokens: 1.2,
    usdCostPerMillionOutputTokens: 1.2,
    providers: ["mistral", "fireworks"],
    releaseDate: "2024-04-17",
    tier: "large",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Pixtral 12B 2409",
    modelIdentifier: "pixtral-12b",
    context: 128000,
    usdCostPerMillionInputTokens: 0.15,
    usdCostPerMillionOutputTokens: 0.15,
    providers: ["mistral"],
    releaseDate: "2024-09-11",
    tier: "normal",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Mistral",
    modelName: "Pixtral Large",
    modelIdentifier: "pixtral-large",
    context: 128000,
    usdCostPerMillionInputTokens: 2,
    usdCostPerMillionOutputTokens: 6,
    providers: ["mistral"],
    releaseDate: "2024-11-21",
    tier: "large",
    canGenerateImage: true,
    hasReasoning: false,
  },
  {
    company: "Morph",
    modelName: "Morph V3 Large",
    modelIdentifier: "morph-v3-large",
    context: 33000,
    usdCostPerMillionInputTokens: 0.9,
    usdCostPerMillionOutputTokens: 1.9,
    providers: ["morph"],
    releaseDate: "2024-09-01",
    tier: "normal",
    canGenerateImage: false,
    hasReasoning: false,
  },
  {
    company: "Z.ai",
    modelName: "GLM 4.5V",
    modelIdentifier: "glm-4.5v",
    context: 66000,
    usdCostPerMillionInputTokens: 0.6,
    usdCostPerMillionOutputTokens: 1.8,
    providers: ["zai", "novita"],
    releaseDate: "2024-09-15",
    tier: "normal",
    canGenerateImage: true,
    hasReasoning: false,
  },
];
